### ISSUE TITLE
pytest-dependency - Installation problem

### ISSUE THREAD

**Issue by svanan77** [RKrahl/pytest-dependency#21]
Hi,

I have managed to successfully install pytest-dependency using `pip install`.

Is there a way to install using `conda install` or if not possible using `apt-get install` ? I am facing some dependency issue where unable to use `pip`.

I was checking out http://pytest-dependency.readthedocs.io/en/0.3.1/ and the web, unfortunately had not been lucky.

Hope you can advice.

Thanks.

**Comment by danieljfarrell** [comment]
I wanted to install this using conda too and added it to my channel. You can install with the command,

`conda install -c danieljfarrell_teraview pytest-dependency`

If the @RKrahl wants to upload himself to conda-forge you could use this `meta.yaml` script and the [conda-build](https://conda.io/projects/conda-build/en/latest/resources/commands/conda-build.html) tool.


```yaml
{% set name = "pytest-dependency" %}
{% set version = "0.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/RKrahl/pytest-dependency/archive/0.4.0.tar.gz
  sha256: e7b45cece88fc91de6df7b9ad027da822aacf7a663e499c55811e3f836570e20

build:
  number: 0
  script: "python -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pytest >=3.6.0
  run:
    - python
    - pytest >=3.6.0

about:
  home: https://pypi.org/project/pytest-dependency
  license: Apache 2 license.
  license_family: Apache
  summary: Manage dependencies of tests
  doc_url: https://pytest-dependency.readthedocs.io
  dev_url: https://github.com/RKrahl/pytest-dependency
```
